name: Build and Test Project
on:
  pull_request:

jobs:
  dotnet-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup dotnet
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
        with:
          dotnet-version: '6.0.x'

      - name: Print dotnet version
        run: dotnet --version
      
      - name: Add dotnet nuget source
        run: dotnet nuget add source https://nuget.pkg.github.com/Keyfactor/index.json -n github -u ${{ github.actor }} -p ${{ secrets.V2BUILDTOKEN }} --store-password-in-clear-text

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Test project
        run: dotnet test
